config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :pitches

  resources :projects

end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_pitch, only: [:show, :edit, :update, :destroy]

  # GET /pitches
  # GET /pitches.json
  def index
    @pitches = Pitch.all
  end

  # GET /pitches/1
  # GET /pitches/1.json
  def show
  end

  # GET /pitches/new
  def new
    @pitch = Pitch.new
  end

  # GET /pitches/1/edit
  def edit
  end

  # POST /pitches
  # POST /pitches.json
  def create
    @pitch = Pitch.new(pitch_params)

    respond_to do |format|
      if @pitch.save
        format.html { redirect_to @pitch, notice: 'Pitch was successfully created.' }
        format.json { render :show, status: :created, location: @pitch }
      else
        format.html { render :new }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitches/1
  # PATCH/PUT /pitches/1.json
  def update
    respond_to do |format|
      if @pitch.update(pitch_params)
        format.html { redirect_to @pitch, notice: 'Pitch was successfully updated.' }
        format.json { render :show, status: :ok, location: @pitch }
      else
        format.html { render :edit }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitches/1
  # DELETE /pitches/1.json
  def destroy
    @pitch.destroy
    respond_to do |format|
      format.html { redirect_to pitches_url, notice: 'Pitch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitch
      @pitch = Pitch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pitch_params
      params.require(:pitch).permit(:name, :solution, :comments)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :school, :city, :state, :issue, :problem)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STEAMTruck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pitches/_form.html.erb
<%= form_for(@pitch) do |f| %>
  <% if @pitch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pitch.errors.count, "error") %> prohibited this pitch from being saved:</h2>

      <ul>
      <% @pitch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :solution %><br>
    <%= f.text_area :solution %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitches/edit.html.erb
<h1>Editing pitch</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch %> |
<%= link_to 'Back', pitches_path %>

app/views/pitches/index.html.erb
<h1>Pitches</h1>

<div class= "container">
  <div class= "row">
    <div class= "offset1 span10">
      <table class= "table table-condensed" width= "647">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Solution</th>
            <th>Comments</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pitches.each do |pitch| %>
            <tr>
              <td><%= pitch.name %></td>
              <td><%= pitch.solution %></td>
              <td><%= pitch.comments %></td>
              <td><%= link_to 'Show', pitch %></td>
              <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
              <td><%= link_to 'Destroy', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Pitch', new_pitch_path %>
    </div>
  </div>
</div>

app/views/pitches/new.html.erb
<h1>New pitch</h1>
<div class= "container">
	<div class= "row-fluid">
		<div class= "offset2 span10">
			<%= render 'form' %>

			<%= link_to 'Back', pitches_path %>
		</div>
	</div>
</div>

app/views/pitches/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<h2>
	<strong></strong>	  
	</h2>
	<div class="row">
		<div class="offset2 span8">
		<p>
		  <strong>Name:</strong>
		  <%= @pitch.name %>
		</p>

		<p>
		  <strong>Solution:</strong>
		  <%= @pitch.solution %>
		</p>

		<%= link_to 'Edit', edit_pitch_path(@pitch) %> |
		<%= link_to 'Back', pitches_path %>
		</div>
	</div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :issue %><br>
    <%= f.text_field :issue %>
  </div>
  <div class="field">
    <%= f.label :problem %><br>
    <%= f.text_area :problem %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div class= "container">
  <div class= "row">
    <div class= "offset1 span10">
      <table class= "table table-condensed" width= "647">
      <table>
        <thead>
          <tr >
            <th>Title</th>
            <th>School</th>
            <th>City</th>
            <th>State</th>
            <th>Issue</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.title %></td>
              <td><%= project.school %></td>
              <td><%= project.city %></td>
              <td><%= project.state %></td>
              <td><%= project.issue %></td>
              <td><%= link_to 'Show', project %></td>
              <td><%= link_to 'Edit', edit_project_path(project) %></td>
              <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Project', new_project_path %>
   </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<div class= "container">
	<div class= "row-fluid">
		<div class= "offset2 span10">

		<%= render 'form' %>

		<%= link_to 'Back', projects_path %>
		</div>
	</div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>
  <strong><%= @project.school %></strong>   
  </h2>
  <div class="row">
    <div class="offset2 span8">
      <p>
        <strong>Title:</strong>
        <%= @project.title %>
      </p>
      <p>
        <strong>City:</strong>
        <%= @project.city %>
      </p>

      <p>
        <strong>State:</strong>
        <%= @project.state %>
      </p>

      <p>
        <strong>Issue:</strong>
        <%= @project.issue %>
      </p>

      <p>
        <strong>Problem:</strong>
        <%= @project.problem %>
      </p>

      <%= link_to 'Edit', edit_project_path(@project) %> |
      <%= link_to 'Pitch', pitches_path %> |
      <%= link_to 'Back', projects_path %> 
      
    </div>
  </div>
</div>